<?php

// Plugin definition
$plugin = array(
  'title' => t('Widescreen'),
  'category' => t('NKF Base'),
  'icon' => 'widescreen.png',
  'theme' => 'widescreen',
  'css' => 'widescreen.css',
  'regions' => array(
    'one' => t('One'),
    'two' => t('Two'),
    'three' => t('Three'),
    'four' => t('Four'),
    'five' => t('Five'),
    'six' => t('Six'),
    'seven' => t('Seven'),
    'eight' => t('Eight'),
    'nine' => t('Nine'),
    'ten' => t('Ten')
  ),
);
