<?php

// Plugin definition
$plugin = array(
  'title' => t('Flex'),
  'category' => t('NKF Base'),
  'icon' => 'flex.png',
  'theme' => 'flex',
  'css' => 'flex.css',
  'regions' => array(
    'top' => t('Top'),
    'one' => t('One'),
    'two' => t('Tow'),
    'three' => t('Three'),
    'four' => t('Four'),
    'five' => t('Five'),
    'six' => t('Six'),
    'seven' => t('Seven'),
    'eight' => t('Eight'),
    'nine' => t('Nine'),
    'ten' => t('Ten'),
    'eleven' => t('Eleven'),
    'twelve' => t('Twelve'),
    'bottom' => t('Bottom')
  ),
);
