<?php

// Preprocess function includes
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_html.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_page.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_node.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_field.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_block.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_entity.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_entity_bean_hero.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_entity_bean_card.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_panels_pane.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_paragraph.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_view.inc';
require_once NKF_BASE_PATH . '/includes/preprocess/preprocess_misc.inc';
